### ISSUE TITLE
Flatpak Zoom is not detected

### ISSUE THREAD

**Issue by ikolomiko** [furkansimsekli/classie#2]
Since Flatpak™ version of Zoom™ does not have the executable `zoom` in `$PATH`, the script fails.

**Comment by furkansimsekli** [comment]
Its been 3 weeks :) Since you forked the repo, I though you would fix it. Are you still interested?

**Comment by ikolomiko** [comment]
Whoops, I totally forgot about this issue. Just started working on it!

**Comment by furkansimsekli** [comment]
Fixed at #3
